services:

  postgresdb:
    image: postgres:latest
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocket_italy
    networks:
      - back
    command: -p 5435
    volumes:
      - app-volume:/var/lib/postgresql/data

  pgadmin:
    image: "dpage/pgadmin:latest"
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - back
    volumes:
      - pgadminv:/var/lib/pgadmin

networks:
  back:
    driver: bridge
    
volumes:
  app-volume: #
